[platformio]
default_envs = atoms3r_cam

[env:atoms3r_cam]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_size = 8MB
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

monitor_speed = 921600

build_unflags =
    -std=gnu++11

build_flags =
    -std=gnu++17
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=1
    -mfix-esp32-psram-cache-issue

lib_deps =
    m5stack/M5Unified @ ^0.2.17
